# QUICK SETUP:
# Install Runner `brew install gitlab-runner` & `brew services start gitlab-runner` - https://docs.gitlab.com/runner/install/
# Install Docker - `brew cask install docker`
# Run Docker via GUI
# Run `gitlab-runner exec docker <job>`
# More info in ./doc/development.md

variables:
#  DB: "mysqli"
#  TRAVIS_BUILD_DIR: "$CI_PROJECT_DIR"
  IGNORE_PATHS: "vendor,node_modules"
  PHPUNIT_IGNORE_PATHS: "$IGNORE_PATHS,cli"

cache:
  paths:
    - $HOME/.composer/cache
    - $HOME/.npm

before_script:
  # Check distro.
  - cat /etc/os-release
  # Cleaning up.
  - echo "Cleaning up old ./ci" && rm -rf $CI_PROJECT_DIR/ci
  - echo "Cleaning up old ./moodle" && rm -rf $CI_PROJECT_DIR/moodle
  # apt-utilsInstall correct DB dynamically - MySQL needs some extra work as debian distro defaults to MariaDB.
  - >
    if [ $DB == "mysqli" ]; then
      export DEBIAN_FRONTEND=noninteractive
      apt update && apt install apt-utils -y > /dev/null
      apt update && apt install gnupg wget lsb-release debconf-utils -y > /dev/null
      wget https://dev.mysql.com/get/mysql-apt-config_0.8.15-1_all.deb
      debconf-set-selections <<< 'mysql-apt-config mysql-apt-config/select-product select Ok'
      echo ************************LIST***************************
      debconf-get-selections | grep mysql
      apt update -y > /dev/null
      apt -y install ./mysql-apt-config_0.8.15-1_all.deb > /dev/null
      apt-cache search mysql-server
      apt update -y > /dev/null
      apt install $DBAPT -y
      service --status-all
    else
      apt update && apt install $DBAPT -y > /dev/null
    fi
  - service $DBSERVICE start
  # MySQL/MariaDB special..... Allow for user w/o password.
  #     Setting auth type to mysqlnative - essential for phpdoc to work, but probs good (for testing) anyway...
  #     Credit: https://stackoverflow.com/questions/39281594/error-1698-28000-access-denied-for-user-rootlocalhost.
  - >
    if [ $DB == "mysqli" ] || [ $DB == "mariadb" ]; then
      mysql -e 'USE mysql; SELECT User, Host, plugin FROM mysql.user; UPDATE user SET plugin="mysql_native_password" WHERE User="root"; FLUSH PRIVILEGES; SELECT User, Host, plugin FROM mysql.user;'
      service mysql restart
    fi
  - apt update && apt install git-core npm -y > /dev/null
  - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh | bash
  - source ~/.bashrc
  - nvm install 14.0.0
  - nvm use 14.0.0
  - cd $CI_PROJECT_DIR/..
  - curl -sS https://getcomposer.org/installer | php
  - mv composer.phar /usr/local/bin/composer
  - composer create-project --no-interaction --no-dev --prefer-dist --quiet blackboard-open-source/moodle-plugin-ci ci ^2
  - export PATH="$(cd ci/bin; pwd):$(cd ci/vendor/bin; pwd):$PATH"
  # Change localhost to 127.0.0.1 for phpdoc.
  - moodle-plugin-ci install --db-host=127.0.0.1 --db-type=$DB -vvv

.job_template: &job_definition
  script:
    - EXIT_STATUS=0
    - moodle-plugin-ci phplint || EXIT_STATUS=$? ; echo "EXIT STATUS - $EXIT_STATUS"
    - moodle-plugin-ci phpcpd || EXIT_STATUS=$? ; echo "EXIT STATUS - $EXIT_STATUS"
    - moodle-plugin-ci phpmd || EXIT_STATUS=$? ; echo "EXIT STATUS - $EXIT_STATUS"
    - moodle-plugin-ci phpdoc || EXIT_STATUS=$? ; echo "EXIT STATUS - $EXIT_STATUS"
    - moodle-plugin-ci phpunit --coverage-text -vvv || EXIT_STATUS=$? ; echo "EXIT STATUS - $EXIT_STATUS"
    - moodle-plugin-ci codechecker || EXIT_STATUS=$? ; echo "EXIT STATUS - $EXIT_STATUS"
    - moodle-plugin-ci validate || EXIT_STATUS=$? ; echo "EXIT STATUS - $EXIT_STATUS"
    - moodle-plugin-ci grunt -t css || EXIT_STATUS=$? ; echo "EXIT STATUS - $EXIT_STATUS" # Thanks https://github.com/open-lms-open-source/moodle-plugin-ci/issues/72#issuecomment-358426352
    #    - moodle-plugin-ci savepoints || EXIT_STATUS=$? ; echo "EXIT STATUS - $(tput bold)$EXIT_STATUS$(tput sgr0)"
    - exit $EXIT_STATUS

# Setup jobs as stages to run sequentially.
stages:
  - job1
  - job2
  - job3
#  - job4
#  - job5
#  - job6
#  - job7
#  - job8
#  - job9

# TODO - Only test highest and lowest.
# Test each active version of PHP.
job1:
  <<: *job_definition
  stage: job1
  image: moodlehq/moodle-php-apache:7.2
  variables:
    MOODLE_BRANCH: "MOODLE_35_STABLE"
    DB: mysqli
    DBAPT: mysql-server
    DBSERVICE: mysql

job2:
  <<: *job_definition
  stage: job2
  image: moodlehq/moodle-php-apache:7.2
  variables:
    MOODLE_BRANCH: "MOODLE_35_STABLE"
    DB: mariadb
    DBAPT: mariadb-server
    DBSERVICE: mysql

job3:
  <<: *job_definition
  stage: job3
  image: moodlehq/moodle-php-apache:7.2
  variables:
    MOODLE_BRANCH: "MOODLE_35_STABLE"
    DB: pgsql
    DBAPT: postgresql postgresql-contrib
    DBSERVICE: postgresql

#job4:
#  <<: *job_definition
#  stage: job4
#  image: moodlehq/moodle-php-apache:7.3
#  variables:
#    MOODLE_BRANCH: "MOODLE_35_STABLE"
#    DB: mysqli
#    DBAPT: mysql-server
#    DBSERVICE: mysql
#
#job5:
#  <<: *job_definition
#  stage: job5
#  image: moodlehq/moodle-php-apache:7.3
#  variables:
#    MOODLE_BRANCH: "MOODLE_35_STABLE"
#    DB: mariadb
#    DBAPT: mariadb-server
#    DBSERVICE: mysql
#
#job6:
#  <<: *job_definition
#  stage: job6
#  image: moodlehq/moodle-php-apache:7.3
#  variables:
#    MOODLE_BRANCH: "MOODLE_35_STABLE"
#    DB: pgsql
#    DBAPT: postgresql postgresql-contrib
#    DBSERVICE: postgresql
#
## Only test the earliest and latest supported version of Moodle.
#job7:
#  <<: *job_definition
#  stage: job7
#  image: moodlehq/moodle-php-apache:7.4
#  variables:
#    MOODLE_BRANCH: "MOODLE_39_STABLE"
#    DB: mysqli
#    DBAPT: mysql-server
#    DBSERVICE: mysql
#
#job8:
#  <<: *job_definition
#  stage: job8
#  image: moodlehq/moodle-php-apache:7.4
#  variables:
#    MOODLE_BRANCH: "MOODLE_39_STABLE"
#    DB: mariadb
#    DBAPT: mariadb-server
#    DBSERVICE: mysql
#
#job9:
#  <<: *job_definition
#  stage: job9
#  image: moodlehq/moodle-php-apache:7.4
#  variables:
#    MOODLE_BRANCH: "MOODLE_39_STABLE"
#    DB: pgsql
#    DBAPT: postgresql postgresql-contrib
#    DBSERVICE: postgresql